import * as basicStyleCss from './css/basic.module.css';
import * as basicStyleLess from './less/basic.module.less';

console.log(basicStyleCss.basic);
console.log(basicStyleCss.cascading);
console.log(basicStyleCss.pseudo_class);
console.log(basicStyleCss.at_rule);
console.log(basicStyleCss.selector_list_1);
console.log(basicStyleCss.selector_list_2);
console.log(basicStyleCss.local_class_name_1);
console.log(basicStyleCss.local_class_name_2);
console.log(basicStyleCss.local_class_name_3);
console.log(basicStyleCss.local_class_name_4);
console.log(basicStyleCss.imported);

console.log(basicStyleLess.basic);
console.log(basicStyleLess.nesting_1);
console.log(basicStyleLess.nesting_2);
console.log(basicStyleLess.parent_selector);
console.log(basicStyleLess.parent_selector_1);
console.log(basicStyleLess.cascading);
console.log(basicStyleLess.pseudo_class);
console.log(basicStyleLess.use_mixin);
console.log(basicStyleLess.clearfix);
console.log(basicStyleLess.at_rule);
console.log(basicStyleLess.selector_list_1);
console.log(basicStyleLess.selector_list_2);
console.log(basicStyleLess.local_class_name_1);
console.log(basicStyleLess.local_class_name_2);
console.log(basicStyleLess.local_class_name_3);
console.log(basicStyleLess.local_class_name_4);
